### ISSUE TITLE
Exercises too hard & Tests too strict?

### ISSUE THREAD

**Issue by ifaoji** [42-Short/shortinette#109]
Some tests really test for the edge case of edge cases. Since our focus should be on learning a new language, the edge cases of edge cases don't really need to be covered, especially since there are no evaluations, and they have a time limit of 24h.

Also some exercises are thinking problems, and not language related problems, which might add an unnecessary complexity in some cases.
Maybe the first few exercises should purely focus on learning language features themselves and only the last one need to be a bit more challenging in this regard.

**Comment by FelixBrgm** [comment]
These problems are already being addressed at
- 24h limit -> doesn't exist anymore
- to complex - first should be simpler #152
