### ISSUE TITLE
Some weird things in subjects

### ISSUE THREAD

**Issue by leske42** [42-Short/shortinette#119]
Here is all the weird things from subjects i remember:

- [x] For module 03, both exercise 02 and 04 tells you that the requirement is only to get the given output for the given input, but then the tester checks for a lot more features implemented (which is fine, but subject wording is wrong in that case).
- [x] In module 04, ex02 is worded in very misleading way, many of us interpreted it as running in an infinite loop and updating real time if any change happens to the files. Also even if this is clarified the tester should still handle if the programs we upload accidentally lead to infinite loop (or fork bomb or anything similar really).
- [ ] I know the tester for module 04 ex04 basically accepts any solution, even if you don't collect the output of children, just spawn all of them and let them print on stdout. (but this one is more about tester than subject)
- [x] In module 05, ex03 we are supposed to use `ftkit` for parsing arguments, but this is not in the allowed symbols (even though we have to import it). At the same time, if we use anything else like vector we get failed. Also maybe it should be clarified that an empty brain should still be able to take 1 input because brain size is really just the buffer size in this case.
- [ ] Module 05 ex04 can actually be solved according to subject (this was discovered by Ildi) so that all unique identifiers (even 255) are assigned and it only panics upon overflow (you just need two identifiers and one trailing the other like 1 value behind). But the tester fails for this solution.
- [ ] For module 06 subject says: "every exercise must be part of a virtual cargo workspace", and also: "any exercise you turn in must compile using cargo", but this is not true for ex07. Actually if you leave it as a member of workspace the tester will just fail the whole module.

**Comment by winstonallo** [comment]
Thank you Kamilla! We will fix all of those :)

**Comment by winstonallo** [comment]
We dispatched the 3 that are not solved yet to singular issues, thank you for your feedback
