### ISSUE TITLE
Document and Improve the subjects's mandatory exercises

### ISSUE THREAD

**Issue by FelixBrgm** [42-Short/shortinette#152]
- [x] #153
---
- [x] mod00 - mandatory (00-04)
- [x] mod01 - mandatory (00-04)
- [x] mod02 - mandatory (00-04)
- [x] mod03 - mandatory (00-04)
- [x] #165
---
- [x] #163
- [x] mod06 - mandatory (00-04)
---
- [x] add reference to book and rust by example

**Comment by winstonallo** [comment]
Hello @FelixBrgm! 👋 Thank you for opening your first issue in this repository. We appreciate your contribution to our project!
A maintainer will review your issue soon. If you're reporting a bug, please provide as much detail as possible – including steps to reproduce, expected vs. actual behavior, and any relevant logs or screenshots. The more information you can provide, the better we can assist you.
Thank you for helping us improve our project!

**Comment by FelixBrgm** [comment]
Im currently done with all mandatory exercises and made PR's for them.

During the first Rust Short we didn't really had complaints about bonus exercises which lets us to the decision to not change them for now.
